db.ventas.drop()
db.ventas.insertMany([
    {
        articuloVendido: "Poema de Gilgamesh", 
        pvpUnitario: 14.95, 
        pveUnitario: 7.95, 
        numeroUnidades: 5, 
        fechaVenta: new Date("2015,02,02"), 
        fechaEntrega: new Date("2015,02,011"), 
        cliente: "Universidad Anáhuac",
        vendedor: "La Libroteca",
        retraso: false
    },
    { articuloVendido: "Libro de Job", pvpUnitario: 19.95, pveUnitario: 11.50, numeroUnidades: 8, fechaVenta: new Date("2015,03,09"), fechaEntrega: new Date("2015,03,16"), cliente: "Liceo Europeo", vendedor: "El Rincón de Hemingway", retraso: false},
    { articuloVendido: "Las mil y una noches", pvpUnitario: 9.95, pveUnitario: 5.50, numeroUnidades: 3, fechaVenta: new Date("2015,03,12"), fechaEntrega: new Date("2015,03,19"), cliente: "Los Sauces", vendedor: "La Librería de David", retraso: false},
    { articuloVendido: "Orgullo y prejuicio", pvpUnitario: 11.50, pveUnitario: 6.75, numeroUnidades: 7, fechaVenta: new Date("2015,04,21"), fechaEntrega: new Date("2015,04,28"), cliente: "Mirabal International", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "Cumbres Borrascosas", pvpUnitario: 19.99, pveUnitario: 10.90, numeroUnidades: 2, fechaVenta: new Date("2015,04,27"), fechaEntrega: new Date("2015,05,11"), cliente: "Mirasur", vendedor: "La Librería de David", retraso: true},
    { articuloVendido: "Viaje al fin de la noche", pvpUnitario: 15.75, pveUnitario: 5.50, numeroUnidades: 6, fechaVenta: new Date("2015,05,28"), fechaEntrega: new Date("2015,06,05"), cliente: "Casvi", vendedor: "El Rincón de Hemingway", retraso: true},
    { articuloVendido: "Don Quijote de la Mancha", pvpUnitario: 18.95, pveUnitario: 11.75, numeroUnidades: 5, fechaVenta: new Date("2015,05,28"), fechaEntrega: new Date("2015,06,07"), cliente: "Alcaste", vendedor: "El Rincón de Hemingway", retraso: true},
    { articuloVendido: "Los cuentos de Canterbury", pvpUnitario: 33.95, pveUnitario: 19.90, numeroUnidades: 1, fechaVenta: new Date("2016,02,02"), fechaEntrega: new Date("2016,02,09"), cliente: "José Rodriguez", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "Crimen y castigo", pvpUnitario: 22.75, pveUnitario: 12.50, numeroUnidades: 4, fechaVenta: new Date("2016,02,07"), fechaEntrega: new Date("2016,02,18"), cliente: "Ayalde", vendedor: "The Cervantes Store", retraso: false},
    { articuloVendido: "Los hermanos Karamazov", pvpUnitario: 19.75, pveUnitario: 8.50, numeroUnidades: 12, fechaVenta: new Date("2016,07,15"), fechaEntrega: new Date("2016,07,22"), cliente: "Arenas", vendedor: "La Librería de David", retraso: false},
    { articuloVendido: "Don Quijote de la Mancha", pvpUnitario: 12.99, pveUnitario: 6.89, numeroUnidades: 10, fechaVenta: new Date("2016,07,13"), fechaEntrega: new Date("2016,07,20"), cliente: "British School", vendedor: "El Rincón de Hemingway", retraso: false},
    { articuloVendido: "El hombre invisible", pvpUnitario: 8.20, pveUnitario: 4.85, numeroUnidades: 6, fechaVenta: new Date("2016,10,14"), fechaEntrega: new Date("2016,10,21"), cliente: "Colegio Claret Don Benito", vendedor: "La Libroteca", retraso: false},
    { articuloVendido: "La educación sentimental", pvpUnitario: 13.90, pveUnitario: 6.95, numeroUnidades: 3, fechaVenta: new Date("2017,08,22"), fechaEntrega: new Date("2017,08,29"), cliente: "SEK Alborán", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "Romancero gitano", pvpUnitario: 25.75, pveUnitario: 16.90, numeroUnidades: 18, fechaVenta: new Date("2017,08,20"), fechaEntrega: new Date("2017,08,27"), cliente: "Compañía de María", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "El amor en los tiempos del cólera", pvpUnitario: 50.00, pveUnitario: 25.75, numeroUnidades: 4, fechaVenta: new Date("2017,09,09"), fechaEntrega: new Date("2017,09,16"), cliente: "La Merced", vendedor: "La Libroteca", retraso: false},
    { articuloVendido: "Cien años de soledad", pvpUnitario: 14.25, pveUnitario: 6.25, numeroUnidades: 6, fechaVenta: new Date("2018,09,25"), fechaEntrega: new Date("2018,10,02"), cliente: "Genius Academy", vendedor: "La Libroteca", retraso: true},
    { articuloVendido: "Odisea", pvpUnitario: 17.50, pveUnitario: 10.79, numeroUnidades: 12, fechaVenta: new Date("2018,10,22"), fechaEntrega: new Date("2018,10,29"), cliente: "Instituto Tecnológico de Avanzada", vendedor: "La Librería de David", retraso: false},
    { articuloVendido: "El sonido de la montaña", pvpUnitario: 19.80, pveUnitario: 14.50, numeroUnidades: 7, fechaVenta: new Date("2018,10,16"), fechaEntrega: new Date("2018,10,23"), cliente: "Academia Wissen", vendedor: "La Libroteca", retraso: false},
    { articuloVendido: "El cuaderno dorado", pvpUnitario: 43.45, pveUnitario: 22.50, numeroUnidades: 9, fechaVenta: new Date("2018,11,17"), fechaEntrega: new Date("2018,11,24"), cliente: "Colegio Calasanz", vendedor: "The Cervantes Store", retraso: false},
    { articuloVendido: "Diario de un loco", pvpUnitario: 8.95, pveUnitario: 5.99, numeroUnidades: 22, fechaVenta: new Date("2019,03,01"), fechaEntrega: new Date("2019,03,08"), cliente: "Universidad Anáhuac", vendedor: "The Cervantes Store", retraso: false},
    { articuloVendido: "La montaña mágica", pvpUnitario: 12.99, pveUnitario: 5.99, numeroUnidades: 4, fechaVenta: new Date("2019,03,04"), fechaEntrega: new Date("2019,03,11"), cliente: "Universidad Sevilla", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "Libro del desasosiego", pvpUnitario: 33.50, pveUnitario: 15.50, numeroUnidades: 17, fechaVenta: new Date("2019,04,07"), fechaEntrega: new Date("2019,04,14"), cliente: "Casvi", vendedor: "La Libroteca", retraso: false},
    { articuloVendido: "Las metamorfosis", pvpUnitario: 46.25, pveUnitario: 22.50, numeroUnidades: 7, fechaVenta: new Date("2019,04,06"), fechaEntrega: new Date("2019,04,13"), cliente: "Los Sauces", vendedor: "La Libroteca", retraso: false},
    { articuloVendido: "En busca del tiempo perdido", pvpUnitario: 6.99, pveUnitario: 3.95, numeroUnidades: 3, fechaVenta: new Date("2019,05,24"), fechaEntrega: new Date("2019,06,01"), cliente: "Universidad Sevilla", vendedor: "La Librería de David", retraso: true},
    { articuloVendido: "Ensayo sobre la ceguera", pvpUnitario: 19.75, pveUnitario: 10.75, numeroUnidades: 2, fechaVenta: new Date("2020,07,05"), fechaEntrega: new Date("2020,07,12"), cliente: "Colegio Claret Don Benito", vendedor: "El Rincón de Hemingway", retraso: false},
    { articuloVendido: "Hamlet", pvpUnitario: 18.70, pveUnitario: 9.99, numeroUnidades: 22, fechaVenta: new Date("2020,09,29"), fechaEntrega: new Date("2020,10,06"), cliente: "Alejandrías", vendedor: "Genius Academy", retraso: true},
    { articuloVendido: "La muerte de Iván Ilich", pvpUnitario: 33.45, pveUnitario: 16.90, numeroUnidades: 40, fechaVenta: new Date("2020,10,23"), fechaEntrega: new Date("2020,10,30"), cliente: "Mirabal International", vendedor: "La Librería de David", retraso: false},
    { articuloVendido: "Memorias de Adriano", pvpUnitario: 12.50, pveUnitario: 6.75, numeroUnidades: 1, fechaVenta: new Date("2021,01,19"), fechaEntrega: new Date("2021,02,26"), cliente: "Ana Benitez", vendedor: "The Book Zone", retraso: false},
    { articuloVendido: "La señora Dalloway", pvpUnitario: 55.55, pveUnitario: 35.90, numeroUnidades: 5, fechaVenta: new Date("2021,02,21"), fechaEntrega: new Date("2021,02,28"), cliente: "Mirabal International", vendedor: "La Librería de David", retraso: false},
    { articuloVendido: "Los viajes de Gulliver", pvpUnitario: 16.99, pveUnitario: 8.75, numeroUnidades: 17, fechaVenta: new Date("2021,02,01"), fechaEntrega: new Date("2021,02,08"), cliente: "Colegio Claret Don Benito", vendedor: "El Rincón de Hemingway", retraso: false},
    
])